version: '3'

services:
  mongo:
    container_name: 'mongo-employee-registry-service'
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: employee_registry_service
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - '27017:27017'