# server
server:
  port: ${PORT:8080}

### spring
spring:
  application:
    name: employee-registry-service
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://employee_registry_service:toor@localhost:27017/admin}

### logging
logging:
  level:
    root: INFO
    com:
      example: TRACE

### actuator
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

### information
info:
  app:
    name: "employee-registry-service"
    description: "a little project for study"
  author: "Jonatha Lacerda"
  java-version: ${java.version}